# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CoffeeTasters' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CoffeeTasters
  pod 'TPKeyboardAvoiding', '~> 1.3'
  pod 'Alamofire', '~> 4.4'
  pod 'AlamofireImage', '~> 3.2'
  pod 'AlamofireObjectMapper', '~> 4.1'

  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'

  target 'CoffeeTastersTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
